### ISSUE TITLE
SSR and prefix breaks layout 

### ISSUE THREAD

**Issue by hampusohlsson** [nachoaIvarez/flexbox-react#24]
Hey @nachoaIvarez 

Thanks for building this lib, works great, most of the time. However, in my SSR app the server rendered output does not validate so the layout is broken for a split second before the client JS kicks in. 

![vjcp1pu](https://cloud.githubusercontent.com/assets/675092/23976671/ab3daf24-09bf-11e7-8c2d-6e43ac40ae27.png)

Using Chrome 56. As you can see, the browser complains about `Invalid property value`. Seems to be a problem with how the prefix is generated for the display property. For the `display` prop, the rules should probably be rendered as individual rows like so:

```css
display: -webkit-box;
display: -ms-flexbox;
display: -webkit-flex;
display: flex;
```

**Comment by hampusohlsson** [comment]
Btw, I looked through your source-code and saw that you depend on [rofrischmann/inline-style-prefixer](https://github.com/rofrischmann/inline-style-prefixer) which is probably generating those properties.. Digging even deeper, this style of concatenating display props seem to have originated from internal behavior in the React core, see https://github.com/facebook/react/issues/2020.

Edit:    
~~My guess is there was an update to Chrome that removed the support for this style of css?~~
Support was dropped in React 15.

**Comment by nachoaIvarez** [comment]
Mhm. So, while this approach you are proposing works, it doesn't quite follows the API design I intended with this library, which is not having a single proprietary concept on it. To use this library you don't need to learn anything. And having a `noPrefix` doesn't continues that idea, I'm afraid. I'm starting to think the best approach would be to get rid of `inline-style-prefixer` and move to something like `glamor`, `aphrodite`, or `styled-components` under the hood. Yes, this would imply a major re-write of the library, but the library is not big, so it's totally doable. I feel bad because I'm genuinely grateful to you for taking the time to submit an issue, investigate on it and submit a PR, but this is not the approach we should follow, in my opinion. Ideally everything should work as it is, both SSR and CSR, in a frictionless, transparent way. I'll try to migrate to `glamor`, `aphrodite`, or `styled-components` shortly and see how it goes.

**Comment by hampusohlsson** [comment]
That makes sense. I'm using `styled-components` and their v2/next branch... works great with SSR! I'll use my own fork of your lib in the meantime, let me know if you need any help!

**Comment by nachoaIvarez** [comment]
Hey @hampusohlsson, I have good news.

All of those libraries I mentioned on my comment (`glamor`, `aphrodite`, or `styled-components`) are listed [here](https://github.com/rofrischmann/inline-style-prefixer#community), using the library. They are using the [static version](https://github.com/rofrischmann/inline-style-prefixer#dynamic-vs-static) of the library. It's actually a minimal change!

I'll publish the fix right away. And the size of the library is going to be smaller now!

**Comment by hampusohlsson** [comment]
Hey, thanks for the quick turnaround. I actually tried that, but the static version also outputs concatenated string so it is the same problem -even worse actually, the layout doesn't work at all since the client code uses the same property.

**Comment by nachoaIvarez** [comment]
But that's weird, `styled-components`, `glamor` and all those libraries work when SSR 🤔

**Comment by hampusohlsson** [comment]
The issue is that you can't do the right thing using inline styles (one display prop on each row). Styled-components outputs classnames with css injected into the body, so they have no problem generating multiple lines.

**Comment by nachoaIvarez** [comment]
Ok, copied. I will resume my `styled-components` port.

**Comment by nachoaIvarez** [comment]
[v4.3.0](https://github.com/nachoaIvarez/flexbox-react/commit/00001e681062d301ff1465addcdb7fe35daa17f5) is up @hampusohlsson. Should be working now.

**Comment by hampusohlsson** [comment]
Wow! That was fast 😅   will try it out in a few hours.

**Comment by hampusohlsson** [comment]
Hey @nachoaIvarez, I just tried `v4.3.0` but my SSR doesn't render any output -- I see that you are using `styled-components@1.4.4` in the `package.json`. It's the `styled-components@next` branch that has support for SSR. If you don't want to rely on a third party beta branch, perhaps you too could create a `next` branch that does until `styled-components v2` lands in master?

**Comment by hampusohlsson** [comment]
FYI, works perfectly with styled-components v2! Just tried it in a local branch 😄
