### ISSUE TITLE
display instead of inline

### ISSUE THREAD

**Issue by olistic** [nachoaIvarez/flexbox-react#8]
From the README:

> You should not learn any proprietary syntax, classnames or API's for this. If you know how to use flexbox, you know how to use flexbox-react components.

So wouldn't you consider changing the API to receive the `display` prop instead of the `inline` prop? `display` would default to `'flex'` and could also be set to `'inline-flex'` if desired.

**Comment by nareshbhatia** [comment]
I am wondering why `display: flex` is the default? If I am trying to create a child (flex item) and only need `flex: 1`, there doesn't seem to be a way of doing this. As far as I can tell, child will also get `display: flex`.

**Comment by nareshbhatia** [comment]
@nachoaIvarez, would you consider changing the default value of `display` to `block`. I think it makes more sense because container-type elements (like `<div>`, `<article>`, `<p>`, etc.) are all `block` elements by default. This will allow us to set `display: flex` only if we want to. This solves the use case of the flex item which does not need to be `display: flex`. I can send you a PR if it makes sense.
